-- Creates a simple SQLite table containing all ISO 3166 Country Codes (as PRIMARY KEY),
-- printable country names, and their approximate latitude/longitude location values.
--
-- Author: John Soprych, 2015
--
-- The author disclaims copyright to this source code.  In place of
-- a legal notice, here is a blessing:
--
--    May you do good and not evil.
--    May you find forgiveness for yourself and forgive others.
--    May you share freely, never taking more than you give.
--

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE country(
id VARCHAR(2) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
lat NUMBER,
lon NUMBER
);
INSERT INTO "country" VALUES('AD','Andorra',42.5,1.5);
INSERT INTO "country" VALUES('AE','United Arab Emirates',24,54);
INSERT INTO "country" VALUES('AF','Afghanistan',33,65);
INSERT INTO "country" VALUES('AG','Antigua and Barbuda',17.05,-61.8);
INSERT INTO "country" VALUES('AI','Anguilla',18.25,-63.17);
INSERT INTO "country" VALUES('AL','Albania',41,20);
INSERT INTO "country" VALUES('AM','Armenia',40,45);
INSERT INTO "country" VALUES('AN','Netherlands Antilles',12.25,-68.75);
INSERT INTO "country" VALUES('AO','Angola',-12.5,18.5);
INSERT INTO "country" VALUES('AP','Asia/Pacific Region',35,105);
INSERT INTO "country" VALUES('AQ','Antarctica',-90,0);
INSERT INTO "country" VALUES('AR','Argentina',-34,-64);
INSERT INTO "country" VALUES('AS','American Samoa',-14.33,-170);
INSERT INTO "country" VALUES('AT','Austria',47.33,13.33);
INSERT INTO "country" VALUES('AU','Australia',-27,133);
INSERT INTO "country" VALUES('AW','Aruba',12.5,-69.97);
INSERT INTO "country" VALUES('AZ','Azerbaijan',40.5,47.5);
INSERT INTO "country" VALUES('BA','Bosnia and Herzegovina',44,18);
INSERT INTO "country" VALUES('BB','Barbados',13.17,-59.53);
INSERT INTO "country" VALUES('BD','Bangladesh',24,90);
INSERT INTO "country" VALUES('BE','Belgium',50.83,4);
INSERT INTO "country" VALUES('BF','Burkina Faso',13,-2);
INSERT INTO "country" VALUES('BG','Bulgaria',43,25);
INSERT INTO "country" VALUES('BH','Bahrain',26,50.55);
INSERT INTO "country" VALUES('BI','Burundi',-3.5,30);
INSERT INTO "country" VALUES('BJ','Benin',9.5,2.25);
INSERT INTO "country" VALUES('BM','Bermuda',32.33,-64.75);
INSERT INTO "country" VALUES('BN','Brunei Darussalam',4.5,114.67);
INSERT INTO "country" VALUES('BO','Bolivia',-17,-65);
INSERT INTO "country" VALUES('BR','Brazil',-10,-55);
INSERT INTO "country" VALUES('BS','Bahamas',24.25,-76);
INSERT INTO "country" VALUES('BT','Bhutan',27.5,90.5);
INSERT INTO "country" VALUES('BV','Bouvet Island',-54.43,3.4);
INSERT INTO "country" VALUES('BW','Botswana',-22,24);
INSERT INTO "country" VALUES('BY','Belarus',53,28);
INSERT INTO "country" VALUES('BZ','Belize',17.25,-88.75);
INSERT INTO "country" VALUES('CA','Canada',60,-95);
INSERT INTO "country" VALUES('CC','Cocos (Keeling) Islands',-12.5,96.83);
INSERT INTO "country" VALUES('CD','Congo, The Democratic Republic of the',0,25);
INSERT INTO "country" VALUES('CF','Central African Republic',7,21);
INSERT INTO "country" VALUES('CG','Congo',-1,15);
INSERT INTO "country" VALUES('CH','Switzerland',47,8);
INSERT INTO "country" VALUES('CI','Cote d"Ivoire',8,-5);
INSERT INTO "country" VALUES('CK','Cook Islands',-21.23,-159.77);
INSERT INTO "country" VALUES('CL','Chile',-30,-71);
INSERT INTO "country" VALUES('CM','Cameroon',6,12);
INSERT INTO "country" VALUES('CN','China',35,105);
INSERT INTO "country" VALUES('CO','Colombia',4,-72);
INSERT INTO "country" VALUES('CR','Costa Rica',10,-84);
INSERT INTO "country" VALUES('CU','Cuba',21.5,-80);
INSERT INTO "country" VALUES('CV','Cape Verde',16,-24);
INSERT INTO "country" VALUES('CX','Christmas Island',-10.5,105.67);
INSERT INTO "country" VALUES('CY','Cyprus',35,33);
INSERT INTO "country" VALUES('CZ','Czech Republic',49.75,15.5);
INSERT INTO "country" VALUES('DE','Germany',51,9);
INSERT INTO "country" VALUES('DJ','Djibouti',11.5,43);
INSERT INTO "country" VALUES('DK','Denmark',56,10);
INSERT INTO "country" VALUES('DM','Dominica',15.42,-61.33);
INSERT INTO "country" VALUES('DO','Dominican Republic',19,-70.67);
INSERT INTO "country" VALUES('DZ','Algeria',28,3);
INSERT INTO "country" VALUES('EC','Ecuador',-2,-77.5);
INSERT INTO "country" VALUES('EE','Estonia',59,26);
INSERT INTO "country" VALUES('EG','Egypt',27,30);
INSERT INTO "country" VALUES('EH','Western Sahara',24.5,-13);
INSERT INTO "country" VALUES('ER','Eritrea',15,39);
INSERT INTO "country" VALUES('ES','Spain',40,-4);
INSERT INTO "country" VALUES('ET','Ethiopia',8,38);
INSERT INTO "country" VALUES('EU','Europe',47,8);
INSERT INTO "country" VALUES('FI','Finland',64,26);
INSERT INTO "country" VALUES('FJ','Fiji',-18,175);
INSERT INTO "country" VALUES('FK','Falkland Islands (Malvinas)',-51.75,-59);
INSERT INTO "country" VALUES('FM','Micronesia, Federated States of',6.92,158.25);
INSERT INTO "country" VALUES('FO','Faroe Islands',62,-7);
INSERT INTO "country" VALUES('FR','France',46,2);
INSERT INTO "country" VALUES('GA','Gabon',-1,11.75);
INSERT INTO "country" VALUES('GB','United Kingdom',54,-2);
INSERT INTO "country" VALUES('GD','Grenada',12.12,-61.67);
INSERT INTO "country" VALUES('GE','Georgia',42,43.5);
INSERT INTO "country" VALUES('GF','French Guiana',4,-53);
INSERT INTO "country" VALUES('GH','Ghana',8,-2);
INSERT INTO "country" VALUES('GI','Gibraltar',36.18,-5.37);
INSERT INTO "country" VALUES('GL','Greenland',72,-40);
INSERT INTO "country" VALUES('GM','Gambia',13.47,-16.57);
INSERT INTO "country" VALUES('GN','Guinea',11,-10);
INSERT INTO "country" VALUES('GP','Guadeloupe',16.25,-61.58);
INSERT INTO "country" VALUES('GQ','Equatorial Guinea',2,10);
INSERT INTO "country" VALUES('GR','Greece',39,22);
INSERT INTO "country" VALUES('GS','South Georgia and the South Sandwich Islands',-54.5,-37);
INSERT INTO "country" VALUES('GT','Guatemala',15.5,-90.25);
INSERT INTO "country" VALUES('GU','Guam',13.47,144.78);
INSERT INTO "country" VALUES('GW','Guinea-Bissau',12,-15);
INSERT INTO "country" VALUES('GY','Guyana',5,-59);
INSERT INTO "country" VALUES('HK','Hong Kong',22.25,114.17);
INSERT INTO "country" VALUES('HM','Heard Island and McDonald Islands',-53.1,72.52);
INSERT INTO "country" VALUES('HN','Honduras',15,-86.5);
INSERT INTO "country" VALUES('HR','Croatia',45.17,15.5);
INSERT INTO "country" VALUES('HT','Haiti',19,-72.42);
INSERT INTO "country" VALUES('HU','Hungary',47,20);
INSERT INTO "country" VALUES('ID','Indonesia',-5,120);
INSERT INTO "country" VALUES('IE','Ireland',53,-8);
INSERT INTO "country" VALUES('IL','Israel',31.5,34.75);
INSERT INTO "country" VALUES('IN','India',20,77);
INSERT INTO "country" VALUES('IO','British Indian Ocean Territory',-6,71.5);
INSERT INTO "country" VALUES('IQ','Iraq',33,44);
INSERT INTO "country" VALUES('IR','Iran, Islamic Republic of',32,53);
INSERT INTO "country" VALUES('IS','Iceland',65,-18);
INSERT INTO "country" VALUES('IT','Italy',42.83,12.83);
INSERT INTO "country" VALUES('JM','Jamaica',18.25,-77.5);
INSERT INTO "country" VALUES('JO','Jordan',31,36);
INSERT INTO "country" VALUES('JP','Japan',36,138);
INSERT INTO "country" VALUES('KE','Kenya',1,38);
INSERT INTO "country" VALUES('KG','Kyrgyzstan',41,75);
INSERT INTO "country" VALUES('KH','Cambodia',13,105);
INSERT INTO "country" VALUES('KI','Kiribati',1.42,173);
INSERT INTO "country" VALUES('KM','Comoros',-12.17,44.25);
INSERT INTO "country" VALUES('KN','Saint Kitts and Nevis',17.33,-62.75);
INSERT INTO "country" VALUES('KP','Korea, Democratic People"s Republic of',40,127);
INSERT INTO "country" VALUES('KR','Korea, Republic of',37,127.5);
INSERT INTO "country" VALUES('KW','Kuwait',29.34,47.66);
INSERT INTO "country" VALUES('KY','Cayman Islands',19.5,-80.5);
INSERT INTO "country" VALUES('KZ','Kazakhstan',48,68);
INSERT INTO "country" VALUES('LA','Lao People"s Democratic Republic',18,105);
INSERT INTO "country" VALUES('LB','Lebanon',33.83,35.83);
INSERT INTO "country" VALUES('LC','Saint Lucia',13.88,-61.13);
INSERT INTO "country" VALUES('LI','Liechtenstein',47.17,9.53);
INSERT INTO "country" VALUES('LK','Sri Lanka',7,81);
INSERT INTO "country" VALUES('LR','Liberia',6.5,-9.5);
INSERT INTO "country" VALUES('LS','Lesotho',-29.5,28.5);
INSERT INTO "country" VALUES('LT','Lithuania',56,24);
INSERT INTO "country" VALUES('LU','Luxembourg',49.75,6.17);
INSERT INTO "country" VALUES('LV','Latvia',57,25);
INSERT INTO "country" VALUES('LY','Libyan Arab Jamahiriya',25,17);
INSERT INTO "country" VALUES('MA','Morocco',32,-5);
INSERT INTO "country" VALUES('MC','Monaco',43.73,7.4);
INSERT INTO "country" VALUES('MD','Moldova, Republic of',47,29);
INSERT INTO "country" VALUES('ME','Montenegro',42,19);
INSERT INTO "country" VALUES('MG','Madagascar',-20,47);
INSERT INTO "country" VALUES('MH','Marshall Islands',9,168);
INSERT INTO "country" VALUES('MK','Macedonia',41.83,22);
INSERT INTO "country" VALUES('ML','Mali',17,-4);
INSERT INTO "country" VALUES('MM','Myanmar',22,98);
INSERT INTO "country" VALUES('MN','Mongolia',46,105);
INSERT INTO "country" VALUES('MO','Macao',22.17,113.55);
INSERT INTO "country" VALUES('MP','Northern Mariana Islands',15.2,145.75);
INSERT INTO "country" VALUES('MQ','Martinique',14.67,-61);
INSERT INTO "country" VALUES('MR','Mauritania',20,-12);
INSERT INTO "country" VALUES('MS','Montserrat',16.75,-62.2);
INSERT INTO "country" VALUES('MT','Malta',35.83,14.58);
INSERT INTO "country" VALUES('MU','Mauritius',-20.28,57.55);
INSERT INTO "country" VALUES('MV','Maldives',3.25,73);
INSERT INTO "country" VALUES('MW','Malawi',-13.5,34);
INSERT INTO "country" VALUES('MX','Mexico',23,-102);
INSERT INTO "country" VALUES('MY','Malaysia',2.5,112.5);
INSERT INTO "country" VALUES('MZ','Mozambique',-18.25,35);
INSERT INTO "country" VALUES('NA','Namibia',-22,17);
INSERT INTO "country" VALUES('NC','New Caledonia',-21.5,165.5);
INSERT INTO "country" VALUES('NE','Niger',16,8);
INSERT INTO "country" VALUES('NF','Norfolk Island',-29.03,167.95);
INSERT INTO "country" VALUES('NG','Nigeria',10,8);
INSERT INTO "country" VALUES('NI','Nicaragua',13,-85);
INSERT INTO "country" VALUES('NL','Netherlands',52.5,5.75);
INSERT INTO "country" VALUES('NO','Norway',62,10);
INSERT INTO "country" VALUES('NP','Nepal',28,84);
INSERT INTO "country" VALUES('NR','Nauru',-0.53,166.92);
INSERT INTO "country" VALUES('NU','Niue',-19.03,-169.87);
INSERT INTO "country" VALUES('NZ','New Zealand',-41,174);
INSERT INTO "country" VALUES('OM','Oman',21,57);
INSERT INTO "country" VALUES('PA','Panama',9,-80);
INSERT INTO "country" VALUES('PE','Peru',-10,-76);
INSERT INTO "country" VALUES('PF','French Polynesia',-15,-140);
INSERT INTO "country" VALUES('PG','Papua New Guinea',-6,147);
INSERT INTO "country" VALUES('PH','Philippines',13,122);
INSERT INTO "country" VALUES('PK','Pakistan',30,70);
INSERT INTO "country" VALUES('PL','Poland',52,20);
INSERT INTO "country" VALUES('PM','Saint Pierre and Miquelon',46.83,-56.33);
INSERT INTO "country" VALUES('PR','Puerto Rico',18.25,-66.5);
INSERT INTO "country" VALUES('PS','Palestinian Territory',32,35.25);
INSERT INTO "country" VALUES('PT','Portugal',39.5,-8);
INSERT INTO "country" VALUES('PW','Palau',7.5,134.5);
INSERT INTO "country" VALUES('PY','Paraguay',-23,-58);
INSERT INTO "country" VALUES('QA','Qatar',25.5,51.25);
INSERT INTO "country" VALUES('RE','Reunion',-21.1,55.6);
INSERT INTO "country" VALUES('RO','Romania',46,25);
INSERT INTO "country" VALUES('RS','Serbia',44,21);
INSERT INTO "country" VALUES('RU','Russian Federation',60,100);
INSERT INTO "country" VALUES('RW','Rwanda',-2,30);
INSERT INTO "country" VALUES('SA','Saudi Arabia',25,45);
INSERT INTO "country" VALUES('SB','Solomon Islands',-8,159);
INSERT INTO "country" VALUES('SC','Seychelles',-4.58,55.67);
INSERT INTO "country" VALUES('SD','Sudan',15,30);
INSERT INTO "country" VALUES('SE','Sweden',62,15);
INSERT INTO "country" VALUES('SG','Singapore',1.37,103.8);
INSERT INTO "country" VALUES('SH','Saint Helena',-15.93,-5.7);
INSERT INTO "country" VALUES('SI','Slovenia',46,15);
INSERT INTO "country" VALUES('SJ','Svalbard and Jan Mayen',78,20);
INSERT INTO "country" VALUES('SK','Slovakia',48.67,19.5);
INSERT INTO "country" VALUES('SL','Sierra Leone',8.5,-11.5);
INSERT INTO "country" VALUES('SM','San Marino',43.77,12.42);
INSERT INTO "country" VALUES('SN','Senegal',14,-14);
INSERT INTO "country" VALUES('SO','Somalia',10,49);
INSERT INTO "country" VALUES('SR','Suriname',4,-56);
INSERT INTO "country" VALUES('ST','Sao Tome and Principe',1,7);
INSERT INTO "country" VALUES('SV','El Salvador',13.83,-88.92);
INSERT INTO "country" VALUES('SY','Syrian Arab Republic',35,38);
INSERT INTO "country" VALUES('SZ','Swaziland',-26.5,31.5);
INSERT INTO "country" VALUES('TC','Turks and Caicos Islands',21.75,-71.58);
INSERT INTO "country" VALUES('TD','Chad',15,19);
INSERT INTO "country" VALUES('TF','French Southern Territories',-43,67);
INSERT INTO "country" VALUES('TG','Togo',8,1.17);
INSERT INTO "country" VALUES('TH','Thailand',15,100);
INSERT INTO "country" VALUES('TJ','Tajikistan',39,71);
INSERT INTO "country" VALUES('TK','Tokelau',-9,-172);
INSERT INTO "country" VALUES('TM','Turkmenistan',40,60);
INSERT INTO "country" VALUES('TN','Tunisia',34,9);
INSERT INTO "country" VALUES('TO','Tonga',-20,-175);
INSERT INTO "country" VALUES('TR','Turkey',39,35);
INSERT INTO "country" VALUES('TT','Trinidad and Tobago',11,-61);
INSERT INTO "country" VALUES('TV','Tuvalu',-8,178);
INSERT INTO "country" VALUES('TW','Taiwan',23.5,121);
INSERT INTO "country" VALUES('TZ','Tanzania, United Republic of',-6,35);
INSERT INTO "country" VALUES('UA','Ukraine',49,32);
INSERT INTO "country" VALUES('UG','Uganda',1,32);
INSERT INTO "country" VALUES('UM','United States Minor Outlying Islands',19.28,166.6);
INSERT INTO "country" VALUES('US','United States',38,-97);
INSERT INTO "country" VALUES('UY','Uruguay',-33,-56);
INSERT INTO "country" VALUES('UZ','Uzbekistan',41,64);
INSERT INTO "country" VALUES('VA','Holy See (Vatican City State)',41.9,12.45);
INSERT INTO "country" VALUES('VC','Saint Vincent and the Grenadines',13.25,-61.2);
INSERT INTO "country" VALUES('VE','Venezuela',8,-66);
INSERT INTO "country" VALUES('VG','Virgin Islands, British',18.5,-64.5);
INSERT INTO "country" VALUES('VI','Virgin Islands, U.S.',18.33,-64.83);
INSERT INTO "country" VALUES('VN','Vietnam',16,106);
INSERT INTO "country" VALUES('VU','Vanuatu',-16,167);
INSERT INTO "country" VALUES('WF','Wallis and Futuna',-13.3,-176.2);
INSERT INTO "country" VALUES('WS','Samoa',-13.58,-172.33);
INSERT INTO "country" VALUES('YE','Yemen',15,48);
INSERT INTO "country" VALUES('YT','Mayotte',-12.83,45.17);
INSERT INTO "country" VALUES('ZA','South Africa',-29,24);
INSERT INTO "country" VALUES('ZM','Zambia',-15,30);
INSERT INTO "country" VALUES('ZW','Zimbabwe',-20,30);

COMMIT;
